name: clean_datasets
channels :
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pandas=2.2.2
  - nltk==3.8.1
  - pip=24.0
  - pip:
      - pyarrow
      - fastparquet
      - pytz==2024.1