main:
  project_name: edge_trm_nlp
  experiment_name: dev
data:
  url_dolar: https://www.portafolio.co/indicadores-economicos
  base_url: https://cnnespanol.cnn.com/
  url: https://www.infobae.com/colombia/
  save_directory: ../../data/raw
    #/mnt/external/Raspberry/news_nlp_project
