name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ajusta según la versión que necesites

    - name: Cache Conda
      uses: actions/cache@v2
      with:
        path: ~/conda
        key: conda-${{ runner.os }}-${{ hashFiles('**/conda.yml') }}
        restore-keys: conda-${{ runner.os }}-

    - name: Install Conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p ~/conda
        source ~/conda/etc/profile.d/conda.sh
        conda init bash
        conda config --set always_yes yes --set changeps1 no
        conda info -a

    - name: Create environment
      run: |
        source ~/conda/etc/profile.d/conda.sh
        conda env create -f Pipeline/conda.yml
        conda activate edge_trm_nlp

    - name: Print Working Directory
      run: ls -la Pipeline/download_information

    - name: Run Main Script
      run: |
        source ~/conda/etc/profile.d/conda.sh
        conda activate edge_trm_nlp
        HYDRA_FULL_ERROR=1 python Pipeline/main.py
