name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ajusta según la versión que necesites

    - name: Cache Conda
      uses: actions/cache@v2
      with:
        path: ~/conda
        key: conda-${{ runner.os }}-${{ hashFiles('**/Pipeline/conda.yml') }}
        restore-keys: conda-${{ runner.os }}-

    - name: Install Conda
      run: |
        if [ ! -d "$HOME/conda" ]; then
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/conda
          source $HOME/conda/etc/profile.d/conda.sh
          conda init bash
        else
          echo "Conda is already installed"
        fi
        source $HOME/conda/etc/profile.d/conda.sh
        conda config --set always_yes yes --set changeps1 no
        conda info -a

    - name: Create or Update Environment
      run: |
        source ~/conda/etc/profile.d/conda.sh
        if conda env list | grep edge_trm_nlp; then
          echo "Environment edge_trm_nlp already exists"
          conda activate edge_trm_nlp
          conda env update -f Pipeline/conda.yml --prune
        else
          conda env create -f Pipeline/conda.yml
          conda activate edge_trm_nlp
        fi

    - name: Run MLflow Project - Part 1
      run: |
        source ~/conda/etc/profile.d/conda.sh
        conda activate edge_trm_nlp
        export HYDRA_FULL_ERROR=1
        mlflow run Pipeline/download_information -e main \
            -P timezone=America/Bogota \
            -P url_news=https://news.google.com/topics/CAAqLAgKIiZDQkFTRmdvSUwyMHZNRFZxYUdjU0JtVnpMVFF4T1JvQ1EwOG9BQVAB?hl=es-419&gl=CO&ceid=CO%3Aes-419 \
            -P save_directory=data/ \
            -P artifact_name=News_Scraping

    - name: Run MLflow Project - Part 2
      run: |
        source ~/conda/etc/profile.d/conda.sh
        conda activate edge_trm_nlp
        mlflow run Pipeline/download_information -e dolar \
            -P url_dolar=https://www.portafolio.co/indicadores-economicos \
            -P save_directory=data/
